# name: Publish to PyPI
# on:
#    release:
#      types: [published]
#    workflow_dispatch:

# jobs:
#   build:
#     name: Build and publish release to PyPI
#     runs-on: ubuntu-latest
#     # This uses PyPI trusted publishing
#     environment:
#       name: pypi
#       url: https://pypi.org/p/django-flags
#     permissions:
#       id-token: write
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: 3.12
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip build
#     - name: Build the package
#       run: |
#         python -m build
#     - name: Publish to PyPI
#       uses: pypa/gh-action-pypi-publish@release/v1

name: Bump version workflow

on:
  push:
    branches:
    - main

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: current_version
      run: echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
    - name: bump2version-action         
      uses: FragileTech/bump-version@v1.0.4
      with:
        current_version: "${{ env.current_version }}"
        files: version.md
        commit_name: Your Company Bot
        commit_email: bot@your-company.com
        login: your-bot-login
        token: "${{ secrets.BOT_TOKEN }}"
